export const Movies = [
   {
      name: "Army of the dead",
      desc: "this is a wonderful movie of al time",
      titleImage: "1a.jpg",
      image: "1.jpg",
      category: "Western",
      language: "English",
      year: 2022,
      time: 3,
      video: "",
      rate: 3,
      numberOfReviews: 20,
   },
   {
      name: "The Conjuring",
      desc: "this is a wonderful movie of al time",
      titleImage: "22.jpg",
      image: "2.jpg",
      category: "Thriller",
      language: "Chinese",
      year: 1999,
      time: 4,
      video: "",
      rate: 1,
      numberOfReviews: 2,
   },
   {
      name: "Below her Mouth",
      desc: "this is a wonderful movie of al time",
      titleImage: "33.jpg",
      image: "3.jpg",
      category: "Romantic",
      language: "English",
      year: 1899,
      time: 1,
      video: "",
      rate: 5,
      numberOfReviews: 56,
   },
   {
      name: "Below her Mouth",
      desc: "this is a wonderful movie of al time",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Romantic",
      language: "English",
      year: 1899,
      time: 1,
      video: "",
      rate: 5,
      numberOfReviews: 56,
   },
   {
      name: "Below her Mouth",
      desc: "this is a wonderful movie of al time",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Romantic",
      language: "English",
      year: 1899,
      time: 1,
      video: "",
      rate: 5,
      numberOfReviews: 56,
   },
   {
      name: "Below her Mouth",
      desc: "this is a wonderful movie of al time",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Romantic",
      language: "English",
      year: 1899,
      time: 1,
      video: "",
      rate: 5,
   },
];
