export const Movies = [
   {
      name: "",
      desc: "",
      titleImage: "1a.jpg",
      image: "1.jpg",
      category: "New Testament",
      language: "English",
      year: 1979,
      time: 2,
      video: "",
      rate: 5,
      numberOfReviews: 20,
   },
   {
      name: "Noah",
      desc: "How God destroyed the world  with a great flood. God chose Noah to rescue innocent creatures.",
      titleImage: "22.jpg",
      image: "2.jpg",
      category: "Old Testament",
      language: "English",
      year: 2014,
      time: 2,
      video: "",
      rate: 5,
      numberOfReviews: 2,
   },
   {
      name: "Samson",
      desc: "Samson, a biblical figure, was a strong man chosen by God to deliver the Israelites from their enemies.",
      titleImage: "33.jpg",
      image: "3.jpg",
      category: "Old Testament",
      language: "English",
      year: 2018,
      time: 1.5,
      video: "",
      rate: 4,
      numberOfReviews: 56,
   },
   {
      name: "Joseph",
      desc: "Joseph was sold into slavery by his brothers and later became a powerful ruler in Egypt.",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Old Testament",
      language: "English",
      year: 1995,
      time: 3,
      video: "",
      rate: 3,
      numberOfReviews: 86,
   },
   {
      name: "The Book Of Daniel",
      desc: "Joseph, a biblical figure, was sold into slavery by his brothers and later became a powerful ruler in Egypt.",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Old Testament",
      language: "English",
      year: 2013,
      time: 1.5,
      video: "",
      rate: 5,
      numberOfReviews: 50,
   },
   {
      name: "Jacob",
      desc: "acob's story is filled with ups and downs, starting with his rivalry with his twin brother, Esau",
      titleImage: "55.jpg",
      image: "5.jpg",
      category: "Old Testament",
      language: "English",
      year: 1994,
      time: 1.5,
      video: "",
      rate: 5,
      numberOfReviews:30,
   },
];
